version: '1'

services:
  base:
    image: rc:6
    volumes:
      - ./src:/src
      - ./scripts:/scripts
      - ./res:/res

  nvidia-services:
    extends:
      service: base
    devices:
      - /dev/nvidia0:/dev/nvidia0
    environment:
      NVIDIA_DRIVER_CAPABILITIES: all
    security_opt:
      - label=type:container_runtime_t

  nvidia-smi:
    extends:
      service: nvidia-services
    command: nvidia-smi

  cuda:
    extends:
      service: nvidia-services
    command: python src/readability_classifier/utils/cuda-checker.py

  help:
    extends:
      service: base
    entrypoint: /scripts/help.sh
